### ISSUE TITLE
1.1版本被检测Trojan:Win32/Sabsik.FL.A!ml 1.0没有

### ISSUE THREAD

**Issue by stopyan** [Zerkalo2147/GTAOL-BadSportDetector#3]
1.1版本被WD检测Trojan:Win32/Sabsik.FL.A!ml 1.0没有

**Comment by Zerkalo2147** [comment]
这可能是WD误报了，我用哈勃分析后没有报毒。这是md5：
f9e2df1780ed18d28655c9543b60845d
你也可以自己上传查毒
