### ISSUE TITLE
数值显示出错

### ISSUE THREAD

**Issue by MaoYan5985** [Zerkalo2147/GTAOL-BadSportDetector#4]
![image](https://github.com/Zerkalo2147/GTAOL-BadSportDetector/assets/122714639/4418be56-d16a-4c7a-8717-b8c10e9fbe6a)
没看错的话是显示的6.45，数字超出了显示边界
顺便问一下那个0.45是怎么来的？

**Comment by Zerkalo2147** [comment]
私信加下QQ细聊

**Comment by Zerkalo2147** [comment]
忘了没有私信功能，加下1791079311吧

**Comment by Zerkalo2147** [comment]
恶意值在内存里面是以浮点数记录的，不过通常情况下恶意值是整数。我没有考虑到会出现小数的情况，这是第一次遇到

**Comment by Zerkalo2147** [comment]
这版选用的指针有误，发布比较仓促没有仔细测试。现在1.1.1版本重新选取了更准确的指针，这个问题应该不会再出现了。
